name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.3

    - name: Install .NET
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: 6.0.x

    - name: Clean
      run: dotnet clean OsuHelper.sln && dotnet nuget locals all --clear

    - name: Build & test
      run: dotnet test -c Release -l GitHubActions

    - name: Build & publish
      run: dotnet publish OsuHelper/ -o OsuHelper/bin/Publish/ --configuration Release

    - name: Upload build artifacts
      uses: actions/upload-artifact@v1
      with:
        name: OsuHelper
        path: OsuHelper/bin/Publish/